spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:mysql}:3306/javatechie?useSSL=false
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update





# spring.datasource.url=jdbc:mysql://localhost:3306/employee-management
# spring.datasource.username=root
# spring.datasource.password=12345678
# spring.jpa.hibernate.ddl-auto=update
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

